name: os-file-test

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      
      - name: Setup Python environment
        uses: actions/setup-python@v4.5.0
        with:
           python-version: '3.11'

      - name: Verify Python installation
        run: python -V

      - name: Upgrade PIP
        run:  python -m pip install --upgrade pip

      - name: Run OS Folder and File Test
        run: python os.py